### ISSUE TITLE
Popsicle + nock is breaking the tests?

### ISSUE THREAD

**Issue by radiovisual** [brh55/eth-price#3]
Not sure why, but it seems the build error is coming from popsicle and nock. Popsicle allows the application to run just fine, but it gets in the way of the tests for some reason.

I have a branch where I switched popsicle out for isomorphic-fetch, and the build is running perfectly, with the tests passing.

If you don't have a preference for popsicle, and you don't mind using isomorphic-fetch, [this PR](https://github.com/brh55/eth-price/pull/4) fixes things (and increases code coverage to 100%).

Here is the error coming from the test run:

<pre>
<--- Last few GCs --->

   83320 ms: Mark-sweep 1308.9 (1436.1) -> 1303.6 (1436.1) MB, 763.1 / 0.0 ms [allocation failure] [GC in old space requested].
   84087 ms: Mark-sweep 1303.6 (1436.1) -> 1303.6 (1436.1) MB, 767.0 / 0.0 ms [allocation failure] [GC in old space requested].
   85077 ms: Mark-sweep 1303.6 (1436.1) -> 1311.3 (1411.1) MB, 989.4 / 0.0 ms [last resort gc].
   86036 ms: Mark-sweep 1311.3 (1411.1) -> 1319.1 (1411.1) MB, 958.9 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x292fa58cfb51 <JS Object>
    1: emitError(aka emitError) [/Users/michael/forks/eth-price/node_modules/nock/lib/request_overrider.js:~205] [pc=0x3cca160f95d2] (this=0x292fa5804381 <undefined>,error=0x1bd4c41de3d9 <an Error with map 0x94f528401c1>)
    2: abort [/Users/michael/forks/eth-price/node_modules/nock/lib/request_overrider.js:185] [pc=0x3cca164f0eef] (this=0x136f25638449 <an OverriddenClientRequest with map 0xe7...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x3cca15f079a7
 7: 0x3cca160f95d2

  1 exception

  ✖ test.js exited due to SIGABRT

----------|----------|----------|----------|----------|----------------|
File      |  % Stmts | % Branch |  % Funcs |  % Lines |Uncovered Lines |
----------|----------|----------|----------|----------|----------------|
All files |  Unknown |  Unknown |  Unknown |  Unknown |                |
----------|----------|----------|----------|----------|----------------|

npm ERR! Darwin 16.0.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "test"
npm ERR! node v6.10.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE
npm ERR! eth-price@0.1.3 test: `xo && nyc ava`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the eth-price@0.1.3 test script 'xo && nyc ava'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the eth-price package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     xo && nyc ava
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs eth-price
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls eth-price
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/michael/forks/eth-price/npm-debug.log
</pre>

**Comment by brh55** [comment]
Ah so it was failing because the input validation (stripping of spaces) occurs in the CLI file. However the test files only test the API, so the test didn't have a matching Nock to cause the test to continue the test execution. Looks like this is accounted for in the fetch PR.
